import type { Metadata } from "next";
import { Bruno_Ace, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers"; // استيراد الـ Providers الجديدة

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const bruno = Bruno_Ace({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZEKA | Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans dark", inter.variable)}>
      <body className={bruno.className}>
        <Providers>
          <Header />
          {children}
          <Toaster className="font-bruno!" />
        </Providers>
      </body>
    </html>
  );
}
